baseurl = "https://nimbusforwork.com"
title = "Nimbus for Work"
languageCode = "en"
enableRobotsTXT = true

[taxonomies]
   tag = "tags"
   category = "categories"

[params]
  # Date format
  #dateFormat = "January 2, 2006"
  SiteDescription = "Commercial Cleaning in Singapore"
  googleTagManager = "GTM-5MN4WXN" # GTM !!! not Google googleAnalytics
  heroImage = "/images/bg-hero2.jpg"
  heroTitle = "Experience World-Class Office Cleaning In Singapore Or The Next One is On Us."
  heroSubtitle = "We make office cleaning and office management hassle-free. Try us out by getting a free quote or call +6587874824"
  ogFbAppId = "411933209271939"
  testimonials = [
    {
      image = "/images/jiahui.jpg",
      name = "Jiahui",
      position = "Operations Executive, Collision 8",
      testimonial = "“The Nimbus team are always on the lookout for suggestions to better fit our needs. They have been very involved in our operations from Day 1, always ensuring we have a good cleaning team on duty.. glad to have Nimbus working alongside the team!”"
    },
    {
      image = "/images/eames.jpg",
      name = "Eames",
      position = "Assistant Manager, Hyflux",
      testimonial = "“Daniel always come to my rescue whenever I’m requesting for an urgent help in cleaning services due to various VIPS events… It’s an honor getting to work closely with Daniel for his great leadership in management and a very promising self that he will ensure the task allocated would be settled at a very satisfactory level.”"
    },
    {
      image = "/images/ian.jpg",
      name = "Ian",
      position = "Head of Real Estate, Found.us",
      testimonial = "“We engaged Nimbus for our quarterly carpet cleaning and upholstery services. We were impressed by their professionalism and quality equipment! Would definitely recommend.”"
    }
  ]

# This is displayer in About page.
[params.social]
  # twitter = "kiwicopple"
  facebook = "https://www.facebook.com/nimbusforwork/"
  # googleplus = "Googleplus username"
  # instagram = "https://www.instagram.com/driffftofficial"
  # tumblr = "Tumblr username"
  # flickr = "Flickr username"
  # reddit = "kiwicopple"
  linkedin = "https://www.linkedin.com/company/13430028/"
  # slideshare = "Slideshare username"
  # github = "https://github.com/exaquark"
  # gitlab = "Gitlab username"
  # bitbucket = "Bitbucket username"
  # stackoverflow = "kiwicopple"
  # jsfiddle = "Jsfiddle username"
  # codepen = "Codepen username"
  # deviantart = "Deviantart username"
  # behance = "Behance username"
  # dribbble = "Dribbble username"
  # wordpress = "Wordpress username"
  # medium = "https://medium.com/exaquark/"
  # foursquare = "Foursquare username"
  # xing = "Xing username"
  # quora = "Quora username"
  # youtube = "Youtube username"
  # vimeo = "Vimeo username"
  # whatsapp = "Whatsapp username"
  # skype = "Skype username"
  # snapchat = "Snapchat username"
  # pinterest = "Pinterest username"
  # telegram = "Telegram username"
  # vine = "Vine username"
  # email = "Your email"


# Footer Menu
[[menu.footer]]
  name = "About"
  weight = 1
  identifier = "about"
  url = "/about/"
