[build]
  Command = "npm run images && hugo && npm run build:functions"
  functions = "lambda"
  Publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.33"
  HUGO_ENV = "production"

[[headers]]
  for = "/*"
  [headers.values]
    Link = [
      "</js/amp-v0.js>; rel=preload; as=script",
      "</js/amp-form-0.1.js>; rel=preload; as=script",
      "</js/amp-analytics-0.1.js>; rel=preload; as=script",
      "</js/webfont.js>; rel=preload; as=script",
      "</1000/images/bg-hero.jpg>; rel=preload; as=image",
      "</logo-menu.svg>; rel=preload; as=image",
      "</nimbus-inverted.png>; rel=preload; as=image",
      "</svg/facebook-logo.svg>; rel=preload; as=image",
      "</svg/linkedin-logo.svg>; rel=preload; as=image",
      "</favicon.png>; rel=preload; as=image"
    ]

[[headers]]
 for = "/"
 [headers.values]
   Link = [
   "</js/amp-v0.js>; rel=preload; as=script",
   "</js/amp-form-0.1.js>; rel=preload; as=script",
   "</js/amp-analytics-0.1.js>; rel=preload; as=script",
   "</js/webfont.js>; rel=preload; as=script",
   "</template-images/support.jpg>; rel=preload; as=image",
   "</svg/roller-brush.svg>; rel=preload; as=image",
   "</svg/air-conditioner.svg>; rel=preload; as=image"
   ]

[[headers]]
 for = "/about-us"
 [headers.values]
   Link = [
     "</1000/images/about-us-bg.jpg>; rel=preload; as=image"
   ]

[[headers]]
 for = "/contact-us"
 [headers.values]
   Link = [
     "</1000/images/nimbus-team3.jpg>; rel=preload; as=image"
   ]
