[build]
  Command = "npm run build:functions && npm run images && hugo"
  Functions = ".netlify/functions"
  Publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.33"
  HUGO_ENV = "production"

[[headers]]
 for = "/*"
 [headers.values]
   Link = '''
   </1000/images/bg-hero.jpg>; rel=preload; as=image, \
   </logo-menu.png>; rel=preload; as=image, \
   </favicon.png>; rel=preload; as=font'''
