[build]
  Command = "npm run build:functions && npm run images && hugo"
  Functions = ".netlify/functions"
  Publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.33"
  HUGO_ENV = "production"
