backend:
  name: github
  repo: NimbusForWork/nimbusforwork.com # Path to your Github repository
# backend:
#   name: git-gateway

media_folder: "/static/images" # Folder where user uploaded files should go
public_folder: "/images" # removing path for media - we will decide the path based on the size we need


collections: # A list of collections the CMS should be able to edit
  - name: "services"
    label: "Services"
    folder: "content/services" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Service", name: "title", widget: "string", required: true}
      - {label: "Heading", name: "description", widget: "text", required: true}
      - {label: "Subheading", name: "subheading", widget: "text", required: true}
      - {label: "Hero Image", name: "image", widget: "image"}
      - label: "Reasons"
        name: "reasons"
        widget: "list"
        fields:
          - {label: "Icon", name: "icon", widget: "image"}
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "Reason", name: "reason", widget: "text"}
      - label: "Testimonials"
        name: "testimonials"
        widget: "list"
        fields:
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Position", name: "position", widget: "string"}
          - {label: "Testimonial", name: "testimonial", widget: "string"}
